# Generated by Django 4.2.1 on 2023-05-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantss', to='plants.category')),
            ],
        ),
    ]
